# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - devel

sudo: required
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcurl4-openssl-dev 
#  - Rscript -e "install.packages('curl')"
# - sudo apt-get install libcurl4-openssl-dev

r_packages:
  - devtools
  - withr
  - covr
  - curl

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE)'

notifications:
  email: false